<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXqfteLd\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXqfteLd/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXqfteLd.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXqfteLd\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXqfteLd\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'XqfteLd',
    'container.build_id' => '09d4ba06',
    'container.build_time' => 1581771059,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXqfteLd');
