<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTRDofmh\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTRDofmh/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTRDofmh.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTRDofmh\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerTRDofmh\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'TRDofmh',
    'container.build_id' => 'a5e3dc84',
    'container.build_time' => 1581469968,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTRDofmh');
