<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerG0opfgM\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerG0opfgM/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerG0opfgM.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerG0opfgM\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerG0opfgM\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'G0opfgM',
    'container.build_id' => 'e43bc100',
    'container.build_time' => 1581464187,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerG0opfgM');
